apiVersion: apps/v1
kind: Deployment    # what do you want to create
metadata:
  name: <name>    # name of the deployment
  labels:
    app: <app_name> 
spec:  # specification of the deployment 
  replicas: <number_of_replicas>
  selector:
    matchlabels:
      app: <app_name> 
    template:
      metadata: 
        labels:
          app: <app_name>
      spec:  # specification for the pods
        containers:
        - name: <container_name> 
          image: <container_image>
          ports:
          - containerPort: <container_port>
